### PR TITLE
Test PR builder

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Oooh ... exciting :-)

**Comment by bobsummerwill** [comment]
Why don't you try moving the build configuration to a YAML file sooner rather than later?
I can review/merge right away.

**Comment by chfast** [comment]
Do we have Jenkins setup ready for that?

**Comment by bobsummerwill** [comment]
And we should probably have some kind of NULL test to avoid the test failure above.
I see that one on some of the other repos too (maybe webthree-helpers?).   It's annoying.

**Comment by bobsummerwill** [comment]
"Do we have Jenkins setup ready for that?"
^ The Jenkinsfile thing, you mean?    I'm not sure.    I meant for a circle.yml.

**Pull request closed without merging**
