### PR TITLE
Update to LLVM 3.8 on OS X.

### PR DESCRIPTION
**Pull request by bobsummerwill**

### CODE REVIEW

**Comment by chfast** [comment]
Merge whenever needed.

**Comment by chfast** [comment]
Will be obsolete by #64.

After #64 you can still use pre-built LLVM available on your platform by explicitly passing its location to cmake:

    cmake -DLLVM_DIR=/usr/local/opt/llvm38/lib/llvm-3.8/share/llvm/cmake

**Comment by bobsummerwill** [comment]
Right - so whenever you flip that live by updating the sub-module in libethereum, we're also going to want to look at the Homebrew formula (and maybe at the PPA formula, @chriseth?).   CC @5chdn.

**Comment by chfast** [comment]
EVMJIT not officially support only LLVM 3.8.

In Homebrew you can use llvm38 (by using `-DLLVM_DIR`)
In Ubuntu/PPA there is no LLVM 3.8 freely available, so I suggest building from source. You can try backporting from 16.04 or some other tricks, but I don't have time to do it myself.

In any case, please create separated issues if some change is needed.

**Comment by bobsummerwill** [comment]
So you're going to need to commit https://github.com/ethereum/homebrew-ethereum/pull/67, @chfast, at the same time as we update the version of evmjit used in the libethereum sub-module.

It looks like I updated ethdocs.org on May 11th (https://github.com/ethereum/homestead-guide/commit/39f4562adb372065a43682f318d88111d9235402), so we're currently out of sync between docs and build/release flow.   We should just get those re-aligned ASAP.

**Comment by bobsummerwill** [comment]
I think, @chriseth, that will we also need to re-add that unconditional setting of LLVM_DIR in libethereum's cmake files:

    if (DEFINED APPLE)
         set(LLVM_DIR "/usr/local/opt/llvm38/lib/llvm-3.8/share/llvm/cmake")		
    endif()

Without that, it will drop-back to build-from-source for LLVM (which is what I would like to get to), which would then see us remove that LLVM line from Homebrew (because the package doesn't come via brew), but then I think we'll likely be screwed at runtime, because the dylibs won't be there.

Thoughts, @chfast?   Do spawn new issues if you think we need.      Maybe there are 2 things here.    LLVM to 3.8 on OS X, and LLVM-from-source-enabled-on-OS X.

**Comment by chfast** [comment]
It all depends on your needs. I plan to integrate that soon, we will see what will happen then.

**Comment by bobsummerwill** [comment]
What do you want to do here, @chfast?

**Comment by chfast** [comment]
It's obsoleted. However we should get builds with LLVM from homebrew.

**Pull request closed without merging**
