### PR TITLE
EVMC has been moved out from this repo (use it via a submodule)

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by chfast** [comment]
Looks good but some CMake tricks can be added. I can do them later on.

**Comment by axic** [comment]
@chfast please take over then

**Comment by axic** [comment]
This is bound to the pre-renaming (`EVMC_...`) commit. We should apply those changes separately to leave this PR readable.

**Comment by mratsim** [comment]
The build part of the README should have a git submodule part like so:

```
git submodule update --init --recursive
mkdir build
cd build
cmake ..
cmake --build . --config RelWithDebInfo
```

**Comment by chfast** [comment]
@mratsim fixed, thanks.
@axic Ready to merge?

**Comment by axic** [comment]
@chfast I cannot approve it but it looks good

**Pull request merged**
