### PR TITLE
EVM-C: documentation updates for the query/update

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by chfast** [comment]
I come up with using lists for documenting callback types. See the example containing 2 variants:

```
/// - ::EVM_LOG, evm_variant::data arg1, evm_variant::data arg2
///   @param arg1  The log unindexed data.
///   @param arg2  The log topics. Detailed description about
///                layout in the memory goes here.
/// - ::EVM_SELFDESTRUCT
///   @param arg1 evm_variant::address  The beneficiary address.
```

**Comment by axic** [comment]
@chfast does that removes the original table layout?

**Comment by chfast** [comment]
@axic yes.

**Comment by chfast** [comment]
I extended docs of `evm_update_fn` in https://github.com/ethereum/evmjit/pull/89/commits/c626a53c5f1757431ce2c848a418b5eb443a6bfb of #89.

**Comment by chfast** [comment]
Will you be able to update docs of query function the same way as was done for update?

**Comment by axic** [comment]
@chfast updated!

**Comment by chfast** [comment]
I think I used `@return` instead of `@result` anywhere else, but it does not matter much.

**Comment by axic** [comment]
Oh, didn't notice. This one worked, but feel free to change.

**Pull request merged**
