### PR TITLE
EVM-C: Rework "get code" callback

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by axic** [comment]
This forces the VM to provide a buffer. Can we have both APIs?

This for the non-copying version:
```
typedef const uint8_t* (*evm_view_code_fn)(struct evm_context* context,
                                    const struct evm_address* address,
                                    size_t code_offset,
                                    size_t* buffer_size);
```

**Comment by axic** [comment]
@chfast any comments on the above?

**Comment by chfast** [comment]
In this case, who is responsible for freeing the buffer?

**Comment by axic** [comment]
The client (practically the same code as now).

Perhaps instead of the two versions it would be better introducing an "owned buffer" structure with its own release method.

**Comment by chfast** [comment]
Yes, that's also an option. I want to wait with this until I will be able to get back to go-ethereum...

**Comment by axic** [comment]
@chfast lets focus this week on merging this.

**Comment by chfast** [comment]
This is a lot of focus for this week :D

**Comment by axic** [comment]
We've discussed on Friday the reasons behind all these options and so far the original proposal seems to be the best for two reasons:
- the VM itself usually is able to provide a pointer into the destination memory
- if the memory of the client is passed around, then the client needs to maintain its lifecycle, and this could easily be a DoS vector

**Comment by chfast** [comment]
Implementation in #170 and https://github.com/ethereum/evmjit/pull/172.

**Comment by axic** [comment]
@chfast can we close this?

**Pull request closed without merging**
